# Generated by Django 5.2 on 2025-04-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notes",
            name="count_likes",
            field=models.IntegerField(default=0),
        ),
    ]
