# Generated by Django 5.2 on 2025-04-20 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_notes_count_likes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notes",
            name="count_likes",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
